X-Profiler/xprofiler

.gitignore, README.md, bin/xctl, binding.gyp, lib/clean.js, lib/utils.js, lib/xctl.js, package.json, src/commands/listener.cc, src/commands/listener.h, src/commands/parser.cc, src/commands/parser.h, src/commands/send.cc, src/commands/send.h, src/common.h, src/configure.cc, src/configure.h, src/library/json.hpp, src/logbypass/log.cc, src/logger.cc, src/platform/platform.h, src/platform/unix/ipc.cc, src/platform/win/ipc_win.cc, src/xprofiler.cc, test/config.test.js, test/fixtures/blocking.js, test/fixtures/config.test.js, test/fixtures/logbypass.test.js, test/fixtures/non-blocking.js, xprofiler.js
=> src: implement ipc boilerplate

bin/xprofctl, bin/xprofctl.json, binding.gyp, lib/utils.js, package.json, src/commands/parser.cc, src/commands/send.cc, src/commands/send.h, src/commands/simple/config.cc, src/commands/simple/config.h, src/commands/simple/version.cc, src/commands/simple/version.h, src/common.h, src/configure.cc, src/configure.h, src/platform/platform.h, src/platform/unix/ipc.cc, src/platform/win/ipc_win.cc, test/commands.test.js, test/fixtures/command.test.js, xprofiler.js
- **check xprofiler version:** `xprofctl check_version -p <pid>`
- **check xprofiler config:** `xprofctl get_config -p <pid>`
- **change xprofiler version:** `xprofctl set_version -p <pid> [options]`
=> src: implement simple cmds

src/commands/dump.cc
Replace some complex `#define` macro logic with function template
=> refactor: the action logic

src/commands/report/javascript_stack.cc, src/logger.cc
fix: compile error when node version lt 12.9.0
refactor: improve the logger code
=> pr about first review

package.json
- Travis CI intermittent timeout
- A crash may occur when log output is frequent
- Automatically output a report when the fatal error occurs
Commits:
- [0550381] docs: update how to contribute - By[`hyj1991`](https://github.com/hyj1991)
- [4115e22] fix: compile error when node version lt 12.9.0 - By [`peze`](https://github.com/peze)
- [5674b0e] refactor: improve the logger code - By [`peze`](https://github.com/peze)
- [9ac3b20] fix: ci occasionally timeout(#39) - By [`hyj1991`](https://github.com/hyj1991)
- [94c2905] src: support set fatal error hook (#37) - By [`hyj1991`](https://github.com/hyj1991)
- [85bf5b6] fix: add lock for writing file - By [`hyj1991`](https://github.com/hyj1991)
PR-URL: https://github.com/hyj1991/xprofiler/pull/40
=> release: v1.0.6

lib/xctl.js, src/logger.cc
See https://github.com/nodejs/node/pull/30556
=> fix: ci error with node-v13.6.0 on windows

src/logger.cc, src/platform/unix/ipc.cc, test/logbypass.test.js
the length of the domain socket file shoule be less than sizeof(sockaddr_un.sun_path) - 1
=> fix: check the domain socket file's length

package.json
Commits:
- [ff18203] fix: possible deadlock in `GCEpilogueCallback` 
PR-URL: https://github.com/hyj1991/xprofiler/pull/51
=> release: v1.1.1

package.json
Commits
- [d5b0f9c] src: support logging http statusCode & expired request 
PR-URL: https://github.com/hyj1991/xprofiler/pull/53
=> release v1.2.0

package.json, test/fixtures/non-blocking.js, test/hooks.test.js
- add `autod` for updating dependencies
- adjust test server port from 8443 to 8445
- output fatalerror.diag used for ci failure
=> src: some optimization

package.json
* Support `node-v14.x`
* Patch `http` by default
Commits:
* [81b4ecd] src: add os version in diag report
* [1bef00a] src: update for compatibility with node-v14.x
* [d967467] src: some optimization
* [f693d41] readme: update for new organization
* [db06f94] src: enable monkey-patch of the `http` module by default
PR-URL: https://github.com/X-Profiler/xprofiler/pull/63
=> release v1.2.1

.autod.conf.js, package.json, xprofiler.js
Commits:
* [86e610b] src: check socket path before start
* [b2c7e64] deps: update nlohmann from v3.7.3 to v3.8.0
PR-URL: https://github.com/X-Profiler/xprofiler/pull/74
=> release v1.2.3

package.json
Commits:
* [f07563f] test: update the regexp for location field (diag)
* [8b6eabc] fix: formating error message before using
* [df3987d] fix: compile warning in vs2019 at windows
* [3610483] fix: duplicate process info
PR-URL: https://github.com/X-Profiler/xprofiler/pull/84
=> release v1.2.4

.autod.conf.js, package.json, src/library/json.hpp
- moment from v2.27.0 -> v2.28.0
- uuid from v8.2.0 -> v8.3.0
- yargs from v15.4.1 -> 16.0.3
- nlohmann from v3.8.0 -> 3.9.1
=> deps: update dependencies

package.json
* Support `node-v15.x`
Commits:
* [2c6c698] docs: update demo & binary host
* [7e2c2cc] refactor: refactor the heap log with macros
* [1c82aa5] deps: update dependencies
* [fbfc601] fix: ignore ENOENT error when cleaning logdir
* [956105f] feat: support node-v15.x
PR-URL: https://github.com/X-Profiler/xprofiler/pull/92
=> release v1.2.5

package.json
Ref: https://github.com/codecov/codecov-node/issues/284
=> fix: ignore codecov.io reporting failure

src/commands/cpuprofiler/cpu_profiler.cc
Reference: https://github.com/hyj1991/v8-profiler-next/issues/28
=> fix: potential memory leak (v8) when profiling

src/logbypass/cpu.cc, test/fixtures/logbypass.test.js
https://github.com/X-Profiler/xprofiler/issues/110
=> feat: support cpu_180, cpu_300 & cpu_600

src/commands/cpuprofiler/cpu_profile.cc, src/commands/cpuprofiler/cpu_profile_node.cc, src/logbypass/cpu.cc, test/fixtures/command.test.js, test/fixtures/logbypass.test.js
https://github.com/X-Profiler/xprofiler/issues/110
=> feat: new cpuprofile format

package.json, scripts/7u.js, scripts/common.js, test/fixtures/command.test.js
* Support new cpuprofile format
* Support cpu_180, cpu_300 & cpu_600
Commits:
* [1e3ddb7] feat: new cpuprofile format
* [395a678] feat: support cpu_180, cpu_300 & cpu_600
* [430b13e] deps: update dependencies
* [e6c60e6] feat: support node-v17.x
* [383aacd] (origin/convert_to_typescript, convert_to_typescript) optimize: logic of dump actions
* [d4265d2] deps: update dependencies
* [5a95320] fix: potential memory leak (v8) when profiling
PR-URL: https://github.com/X-Profiler/xprofiler/pull/114
=> release v1.3.0

binding.gyp, package.json, src/library/utils.cc, src/logbypass/gc.cc, src/logbypass/gc.h, src/platform/unix/ipc.cc
* @mapbox/node-pre-gyp from v1.0.6 -> 1.0.8
* autod from 3.1.1 -> 3.1.2
* urllib from 2.37.4 -> 2.38.0
=>  deps: update dependencies

.github/workflows/nodejs.yml, package.json
Commits:
* [170052b] fix: precision loss in (CpuProfileNode*) ptr->GetSampleTimestamp()
* [ca07a81] deps: update dependencies
* [5e5cc23] ci: remove appveryor
* [e588588] ci: build when push tags
PR-URL: https://github.com/X-Profiler/xprofiler/pull/118
=> Release 1.3.1

src/commands/dump.cc, src/commands/gcprofiler/gc_profiler.cc, src/commands/gcprofiler/gc_profiler.h, src/environment_data.h
- Stores GcProfiler states in EnvironmentData
=> feat: per-isolate gc profiler

src/commands/report/heap_statistics.cc, src/commands/report/javascript_stack.cc, src/hooks/fatal_error.cc, src/hooks/fatal_error.h, src/hooks/set_hooks.cc, src/hooks/set_hooks.h, src/util.cc, src/xpf_v8.h
- Print location and message on fatal error.
- Generate diag-report on assertion failures.
=> feat: print location and message on fatal error

src/commands/dump.cc, src/hooks/fatal_error.cc, src/library/common.cc, src/library/common.h, src/library/utils.cc, src/library/utils.h
- Generate diagnostic files with deterministic id.
=> feat: deterministic diagnostic file id generation

binding.gyp, src/environment_data.cc, src/environment_data.h, src/logbypass/log.cc, src/logbypass/log.h, src/process_data.h, src/util-inl.h, src/xpf_mutex-inl.h, src/xpf_mutex.h, src/xpf_thread.cc, src/xpf_thread.h, src/xprofiler.cc
Safely clean up resources at the exit.
=> feat: join-able logbypass thread

binding.gyp, src/environment_data.cc, src/environment_data.h, src/environment_registry.cc, src/environment_registry.h, src/logbypass/log.cc, src/logbypass/log.h, src/process_data.cc, src/process_data.h, src/xprofiler.cc
- Add EnvironmentRegistry
- LogByPass no longer binds to a single EnvironmentData
- AtExit of EnvironmentData only deregisters itself from the registry
=> feat: environment registry

lib/worker_threads.js, src/commands/listener.cc, src/environment_data.cc, src/environment_data.h, src/environment_registry.cc, src/environment_registry.h, src/hooks/set_hooks.cc, src/logbypass/http.cc, src/logbypass/log.cc, src/logger.cc, src/logger.h, src/xprofiler.cc, test/fixtures/utils.js, test/fixtures/worker.js, test/worker_threads.test.js, xprofiler.js
- Properly cleanup uv handles of `EnvironmentData`
- Test loading xprofiler with `worker_threads`
=> feat: context aware native module

bin/xprofctl, src/commands/gcprofiler/gc_profiler.cc, src/commands/simple/registry.cc, src/environment_data.cc, src/environment_data.h, src/library/common.h, src/logbypass/gc.cc, src/platform/unix/cpu.cc, src/platform/win/ipc_win.cc, test/fixtures/command.test.js, test/worker_threads.test.js
- Add tests on measured uptime values.
=> fix: uptime should be measured in seconds

.github/workflows/nodejs.yml, package.json
Reference: https://github.com/X-Profiler/xprofiler/runs/6033975154?check_suite_focus=true
=> fix: clang-format failed on darwin

README.md, src/environment_data.cc, src/environment_data.h, test/fixtures/utils.js
Refs:
- https://github.com/libuv/libuv/blob/v1.x/src/unix/core.c#L226
- https://github.com/libuv/libuv/blob/v1.x/src/unix/core.c#L331
=> fix: use-after-free on environmentdata

src/commands/cpuprofiler/cpu_profile.cc, src/commands/dump.cc, src/commands/gcprofiler/gc_profiler.cc, src/commands/heapdump/heap_snapshot.cc, src/commands/heapprofiler/sampling_heap_profiler.cc, src/commands/listener.cc, src/commands/report/node_report.cc, src/hooks/fatal_error.cc, src/logbypass/http.cc, src/logbypass/log.cc
* 将能判断为 main js thread 或者 worker thread 中输出的 `Info` / `Error` / `Debug` 使用 `InfoT` / `ErrorT` / `DebugT` 替换，方便可能的问题定位需求
=> refactor: log with tid if possible

package.json, scripts/7u.js, test/commands.test.js, test/fixtures/blocking.js, test/fixtures/non-blocking.js, test/fixtures/utils.js, test/fixtures/worker_blocking.js
Commits:
* [ef7d4f3] fix: ensure config dtor order
* [1d81ae2] refactor: log with tid if possible
* [eb97ced] chore: remove useless code
* [fb56fe6] fix: use-after-free on environmentdata
=> Release 2.0.1

package.json, scripts/versions.js
Commits:
* [b2acf60] fix: runtime version in report
* [9e9349b] fix: wrong incremental_marking_duration_last_record value
* [40d4eea] chore: update libs
=> Release 2.1.0

package.json, src/library/json.hpp
例行更新依赖，包括 npm 模块，以及内置的 json 处理库至最新，准备发布 `v2.1.1`
=> chore: update deps

src/commands/dump.cc, src/library/utils.h
Templated `DoDumpAction` function can be specialized with more parameters at build time.
=> chore: static dispatch on dumpaction

.gitignore, test/commands.test.js, test/config.test.js, test/fixtures/cases/command.js, test/fixtures/cases/config.js, test/fixtures/cases/hooks.js, test/fixtures/cases/logbypass.js, test/fixtures/cases/unfinished.js, test/fixtures/scripts/exit.js, test/fixtures/scripts/fatal_error.js, test/fixtures/scripts/process_blocking.js, test/fixtures/scripts/process_normal.js, test/fixtures/scripts/worker_blocking.js, test/fixtures/scripts/worker_indefinite.js, test/fixtures/scripts/worker_normal.js, test/fixtures/utils.js, test/hooks.test.js, test/logbypass.test.js, test/unfinished.test.js, test/worker_threads.test.js
* 修改测试目录结构，使得 `fixtures` 下的文件作用更加清晰
* 调整部分测试超时逻辑，提高资源超卖导致执行慢时 CI 的成功率
=> chore: make test more reliable

package.json, scripts/versions.js
Commits:
* [2f700fd] docs: update readme (#207)
* [f4eb960] feat: support node-v19.x (#206)
* [333593e] chore: make test more reliable (#205)
* [c574ca2] feat: save Elf BuildId in corefile. (#204)
* [b779aa2] feat: support finish profiling before process exit (#203)
* [6a1701f] refactor: replace dump actions static storages with EnvironmentData (#202)
* [7608a86] fix: ignore clean error (#200)
* [2a6eaba] chore: static dispatch on dumpaction (#199)
* [7d3fbb2] optimize: take action (#198)
=> Release 2.3.0

package.json, scripts/versions.js
Commits:
* [8808b04] feat: support auto increase heap limit
=> Release 2.5.0

package.json, scripts/versions.js
Commits:
* [47d814f] feat: support node-v20.x
=> Release 2.5.2

package.json, scripts/versions.js
Commits:
* [6c04b07] fix: crash caused by duplicate configure with worker thread
=> Release v2.5.3

package.json, scripts/versions.js
Commits:
* [98d0810] feat: support mallopt (#238 )
* [319937c] feat: support node-v21.x (#234)
=> Release v2.6.0
