src/logbypass/gc.cc
The `GCEpilogueCallback` function does not release the mutex lock when it return early in some cases, which may cause a deadlock.
=> fix: possible deadlock in `GCEpilogueCallback`

README.md, package.json
Commits:
* [536160b] src: fix: not output js stack on fatal error & update dependencies
* [e4dfb73] feat: use node-pre-gyp instead of node-gyp
PR-URL: https://github.com/X-Profiler/xprofiler/pull/67
=> release v1.2.2

package.json, src/library/utils.h
ref: https://en.cppreference.com/w/cpp/error/exception/what
=> fix: formating error message before using

src/logbypass/gc.h, src/logbypass/heap.h, src/logbypass/libuv.h
Ref: https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-warnings/c5208?view=vs-2019
=> fix: compile warning in vs2019 at windows

lib/clean.js
There is a race condition when multi processes are cleaning logdir.
```
Error: ENOENT: no such file or directory, unlink '/Users/claude/demo/logs/xprofiler-uds-path-17977.sock'
at Object.unlinkSync (fs.js:1136:3)
at /Users/claude/demo/node_modules/xprofiler/lib/clean.js:35:10
at Array.forEach (<anonymous>)
at clean (/Users/claude/demo/node_modules/xprofiler/lib/clean.js:33:13)
at Function.start (/Users/claude/demo/node_modules/xprofiler/xprofiler.js:65:3)
at Object.<anonymous> (/Users/claude/demo/index.js:10:11)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```
=> fix: ignore ENOENT error when cleaning logdir

package.json, scripts/7u.js, scripts/common.js, scripts/copy.js
* Support `node-v16.x`
Commits:
* [c446ebb] chore: using git actions instead of travis ( linux / darwin )
* [b7e23e1] fix: process cpu usage
* [7bea901] fix: ignore codecov.io reporting failure
* [30bcdd1] feat: support node-v16.x
PR-URL: https://github.com/X-Profiler/xprofiler/pull/98
=> release v1.2.6

binding.gyp, package.json, src/library/json.hpp
- `@mapbox/node-pre-gyp` from v1.0.5 -> v1.0.6
- `nan from v2.14.2` -> v2.15.0
- `clang-format from` v1.4.0 -> v1.6.0
- `urllib from v2.37.3` -> v2.37.4
- `nlohmann from v3.9.1` -> 3.10.4
=> deps: update dependencies (#88)

src/library/common.cc
No need to access node versions by calling into JavaScript.
=> fix: get node version from macros

bin/xprofctl, bin/xprofctl.json, binding.gyp, src/commands/dump.cc, src/commands/simple/config.cc, src/configure-inl.h, src/configure.cc, src/configure.h, src/hooks/fatal_error.cc, src/hooks/set_hooks.cc, src/library/common.cc, src/logbypass/libuv.cc, src/logbypass/log.cc, src/logger.cc, src/platform/unix/ipc.cc, src/platform/win/ipc_win.cc, src/util-inl.h, src/util.cc, src/util.h, src/xprofiler.cc, test/fixtures/command.test.js
1. 将每个进程唯一的配置项包装在 `per_process::config_store` 中；
2. 限制性地暴露 config getter/setter（大部分 config 不需要从 c++ set），减少配置变动的暴露面、后续多线程实现更简便；
2. 去除了通过 xprofctl 设置 `enable_fatal_error_hook` 的能力：等到 xprofctl 能设置这个值时，时机已经过去了，这个设置其实是不生效的；
3. 增加 OneByteString helper，配置项 key 都是 ASCII 编码；
=> feat: enclose config slots in per process store

src/commands/report/node_report.cc, src/configure.h, src/library/common.cc, src/library/common.h, src/logger.cc, src/logger.h, src/util.h, src/xprofiler.cc
Move global variables initialization out of binding initialization. The binding initialization function may be called several times when worker_threads is supported.
=> feat: init global variables once at dlopen

.clang-format, binding.gyp, src/environment_data.cc, src/environment_data.h, src/logbypass/cpu.cc, src/logbypass/cpu.h, src/logbypass/gc.cc, src/logbypass/gc.h, src/logbypass/heap.cc, src/logbypass/heap.h, src/logbypass/http.cc, src/logbypass/http.h, src/logbypass/libuv.cc, src/logbypass/libuv.h, src/logbypass/log.cc, src/logbypass/log.h, src/util.h, src/xpf_mutex-inl.h, src/xpf_mutex.h, src/xpf_node.h, src/xprofiler.cc
- Defines`EnvironmentData`. In this PR, a `per_process::environment_data` is used without dynamic registration support.
- Replaces static storage slots of logbypass statistics collection (gc, heap, http, libuv) with EnvironmentData slots.
- logbypass only sends one single uv_async signal to the JavaScript thread to collect heap and uv handles statistics.
=> feat: replace logbypass static storages with EnvironmentData

src/commands/dump.cc, src/commands/heapdump/heap_profiler.cc, src/commands/heapdump/heap_profiler.h, src/commands/heapdump/heap_snapshot.cc, src/commands/heapdump/heap_snapshot.h, src/commands/heapprofiler/sampling_heap_profiler.cc, src/commands/heapprofiler/sampling_heap_profiler.h, src/util.h
- Renames `CHECK` in dump.cc to `CHECK_ERR` to prevent name conflicts with `CHECK` in util.h
- Refactor heap profiler and heap snapshot to be `isolate` specific operations.
=> feat: per-isolate heap profiler

src/commands/dump.cc, src/commands/dump.h, src/commands/listener.cc, src/commands/listener.h, src/commands/parser.h, src/commands/send.h, src/environment_data.cc, src/environment_data.h, src/hooks/fatal_error.h, src/library/utils.h
Refactors dump actions' assumptions on a single isolate per process.
Note that this PR doesn't change the fact that the dump action can only start one single profiling at once for a single process, and probably never going to change that.
=> feat: per-isolate dump actions

.github/workflows/nodejs.yml, package.json, scripts/7u.js, scripts/common.js
Commits:
* [f26e918] fix: get node version from macros
* [077f6e3] feat: enclose config slots in per process store
* [5278a3a] fix: va_list shouldn't be converted to nullptr
* [6848552] feat: init global variables once at dlopen
* [21ade0e] fix: logger va_list argument type
* [3718573] feat: replace logbypass static storages with EnvironmentData
* [c4ced63] fix: replace hex node module version with semantic version macros
* [391d395] feat: per-isolate node report
* [ae6ab8d] chore: optimize content structure (e.g. gcprofile)
* [f78cd6a] feat: per-isolate heap profiler
* [9a931d5] feat: per-isolate gc profiler
* [7184d68] style: pointer alignment
* [5a39e3f] test: check child process exit code
* [95ed727] feat: per-isolate cpu profiler
* [eb5fbc5] feat: print location and message on fatal …
=> Release v1.4.0

.github/workflows/nodejs.yml, package.json, scripts/7u.js, scripts/common.js, src/environment_data.cc
Commits:
* [f26e918] fix: get node version from macros
* [077f6e3] feat: enclose config slots in per process store
* [5278a3a] fix: va_list shouldn't be converted to nullptr
* [6848552] feat: init global variables once at dlopen
* [21ade0e] fix: logger va_list argument type
* [3718573] feat: replace logbypass static storages with EnvironmentData
* [c4ced63] fix: replace hex node module version with semantic version macros
* [391d395] feat: per-isolate node report
* [ae6ab8d] chore: optimize content structure (e.g. gcprofile)
* [f78cd6a] feat: per-isolate heap profiler
* [9a931d5] feat: per-isolate gc profiler
* [7184d68] style: pointer alignment
* [5a39e3f] test: check child process exit code
* [95ed727] feat: per-isolate cpu profiler
* [eb5fbc5] feat: print location and message on fatal …
=> Release 1.4.0

src/environment_registry.cc, src/logbypass/http.cc
- There are chances that after `Environment::AtExit` the JavaScript is still allowed to be executed. GC might still be triggered on the relevant `v8::Isolate`'s heap, which may cause abort on https://github.com/X-Profiler/xprofiler/blob/master/src/logbypass/gc.cc#L35. Allow `EnvironmentRegistry::Get` to return a `nullptr` on such cases.
=> fix: allow EnvironmentRegistry::Get after at-exit

src/commands/gcprofiler/gc_profiler.cc, src/environment_data.cc, src/environment_data.h, src/library/common.cc, src/logbypass/gc.cc
each worker thread has its own uptime.
=> fix: worker_threads uptime

bin/xprofctl, lib/xctl.js, src/commands/dump.cc, src/commands/dump.h, src/commands/parser.cc, src/commands/report/node_report.cc, src/environment_registry.cc, src/environment_registry.h, test/commands.test.js, test/fixtures/command.test.js, test/fixtures/worker_blocking.js, test/worker_threads.test.js
- Run `xprofctl [-w thread_id]` to specify thread to be profiled.
- Add positional parameter `threadId` to `xctl`.
- Add test case worker blocking in `test/command.test.js`.
=> feat: perform profiling actions on worker threads

src/commands/report/node_report.cc, src/environment_data.cc, src/environment_data.h
NodeReport should be lock-free to prevent unexpected dead-lock in abort/CHECK/v8::ApiCheck in arbitrary procedures.
=> feat: lock-free EnvironmentData::TryGetCurrent

src/logger.cc, src/logger.h, test/log.test.js, test/logbypass.test.js
- Rename the first parameter of `Info`/`Debu`/`Erro` to be `component` instead of `type` to be distinguished with LOG_TYPE enum.
=> feat: distinguish log types in different contexts

.autod.conf.js, package.json, scripts/8u.js, scripts/build.js, scripts/common.js, src/commands/cpuprofiler/cpu_profile.cc, src/commands/cpuprofiler/cpu_profiler.cc, src/commands/report/javascript_stack.cc, src/logbypass/heap.cc, src/logbypass/heap.h, src/platform/platform.h, src/platform/unix/core/linux/thread_lister.cc, src/platform/unix/utils.cc, src/platform/win/utils_win.cc, src/xpf_node.h, src/xpf_v8.h, test/log.test.js
由于 `xprofiler@2.x` 最小版本提升至 `node-v12.x`，此 PR 旨在移除一些已经无需使用的实现，具体为：
* 将 SRC 和 Node.js 版本相关的条件判断逻辑移除（涉及到 12.x 以下），使实现更加简洁
=> chore: remove useless code

src/configure-inl.h, src/configure.cc, src/configure.h, src/process_data.h
* 退出前 `logbypass` 在 `config_store` 之后 `Join` 会导致诸如 `logdir` 乱码的问题，收敛到 `ProcessData` 类中保证其在 `Join` 后销毁
=> fix: ensure config dtor order

scripts/build.js, src/commands/report/node_report.cc, src/environment_data.cc, src/environment_data.h, src/library/common.cc, src/library/common.h, xprofiler.js
`diag_report` 中获取的 `nodeVersion` 需要是当前进程正在使用的 Node runtime，`NODE_VERSION` 宏定义则固定为预编译生成时使用的 Node runtime，这样会造成版本错误。
这里在初始化 Env 环境时带上 `process.version`，需要获取 Node runtime 版本处则通过 `env_data` 来进行获取。
=> fix: runtime version in report

LICENSE, binding.gyp, src/library/printf-inl.h, src/library/printf.h, src/logbypass/cpu.cc, src/logbypass/http.cc, src/logger.cc, src/logger.h, src/util.h, test/fixtures/logbypass.test.js, test/logbypass.test.js
定义了宏 `__CHECK_WFORMAT__`  则 logbypass 数据记录前使用 `prinf` 进行校验：
```c++
#if defined(__CHECK_WFORMAT__)
#define RECORD(component, format, args...) \
if (false) {                             \
printf(format, args);                  \
}                                        \
Info(component, format, args);
#define RECORD_T(component, thread_id, format, args...) \
if (false) {                                          \
printf(format, args);                               \
}                                                     \
InfoT(component, thread_id, format, args);
#else
#define RECORD Info
#define RECORD_T InfoT
#endif
```
否则依旧使用原来的 `Info` 和 `InfoT` 进行处理，这样可以在 `npm run build` 对应的编译阶段提供 format 和对应 value 的精度校验，防止出现未定义行为，打包时则通过 `config.gypi` 去除 `__CHECK_WFORMAT__` 以完全使用原来的逻辑进行打包。 …
=> fix: wrong incremental_marking_duration_last_record value

src/commands/gcprofiler/gc_profiler.cc, src/commands/gcprofiler/gc_profiler.h
fix nested gc callback. 
Refs: https://github.com/nodejs/node/pull/44058
=> fix: fix nested gc callback

src/hooks/fatal_error.cc, test/fixtures/logbypass.test.js
`node-v18.8.0` 中的新版 report 实现拦截了 `oom` 事件，使得原本 xprofiler 中的 fatal error hook 无法生效，这里通过增加 oom hook 来避免被 runtime 里面的逻辑覆盖掉
值得注意的是，`enable_fatal_error_coredump` 和 `enable_fatal_error_hook` 配置为 `false` 则不会覆盖 runtime 里面的拦截处理。
Reference: 
* https://github.com/nodejs/node/pull/44242/files#diff-5f2fc380364ef43210af4a28c08f9a0c7ec5f85e3ec1f5c1df5e0204eb9dc721R243
* https://github.com/nodejs/node/pull/44242/files#diff-16cddcd719418092bf9f602309598657f14d1160548cb2803ab98a16328a4f3dR558
=> fix: fatalerror hook not working in node-v18.8.0

src/platform/unix/report.cc
`alpine` 等环境下缺少 `execinfo` 库函数导致 `--build-from-source` 失败。
本 PR 增加 `HAVE_EXECINFO_H` 宏：
```c++
#if defined(__linux__) && !defined(__GLIBC__) || defined(__UCLIBC__) || \
defined(_AIX)
#define HAVE_EXECINFO_H 0
#else
#define HAVE_EXECINFO_H 1
#endif
```
且仅在 `HAVE_EXECINFO_H` 生效时诊断报告输出 Native stack，否则输出空：
```c++
#if HAVE_EXECINFO_H
#include <cxxabi.h>
#include <execinfo.h>
#endif
#if (HAVE_EXECINFO_H)
void PrintNativeStack(JSONWriter* writer) {
// 此时获取 native stack 详细信息
}
#else
void PrintNativeStack(JSONWriter* writer) {
writer->json_arraystart("nativeStacks");
writer->json_arrayend();
}
#endif
```
已在 `alpine@3.16` 上验证通过。
Reference：
* https://github.com/nodejs/node/blob/main/src/debug_utils.cc#L15-L21
=> fix: output native stack if HAVE_EXECINFO_H defined

package.json, scripts/versions.js
Commits:
* [1538d8c] fix: output native trace if HAVE_EXECINFO_H defined (#196)
* [5c594a0] fix: remove upload (#194)
* [b4feaf4] chore: update deps (#193)
* [29d8b72] fix: fatalerror hook not working in node-v18.8.0 (#192)
* [92f651c] fix: fix nested gc callback (#188)
=> Release 2.2.0

src/commands/dump.cc, src/commands/dump.h
早期 1.x 版本在尚未实现 `worker_threads` 监控时，开发者的采样操作会通过 `requestInterrupt` & `uv_async_send` 同时通知js 主线程 —— 这意味着 `HandleAction` 在早期实现中会执行两次。
因此旧版实现中在 `HandleAction` 执行前校验了 `TransactionDone` 这个函数，通过 `${uuid}::${action}` 的唯一 key 设置状态判断当前的 action 是否已经由 `requestInterrupt` or `uv_async_send` 执行过了，如果已经执行过，则清理 data 然后返回。
而在最新的实现中，将 `HandleAction` 放置到一个 lambda 回调中：
```c++
static void NotifyJsThread(EnvironmentData* env_data, void* data) {
env_data->RequestInterrupt(
[data](EnvironmentData* env_data, InterruptKind kind) {
HandleAction(env_data->isolate(), data,
kind == InterruptKind::kBusy ? "v8_request_interrupt" : "uv_async_send");
});
}
```
并且这个回调函数会放入每一个 EnvData 对应的 `std:list` 中，这样 `requestInterrupt` & `uv_async_send` 先触发的那一个会通过 `std::list::swap` 执行回调，后触发拿到的 `std::list` 为空不会再触发。
这样 `HandleAction` …
=> optimize: take action

lib/clean.js
cluster 模式下并发启动 Node 进程可能会重复清理无效的旧 domain socket 文件，这里的错误可以忽略，无需打印出来造成干扰
清理旧 sock 失败不应该影响主流程。
=> fix: ignore clean error

src/commands/dump.cc, src/environment_data.h
目前的 `dump.cc` 中实现的采样动作，依赖全局变量处理，存在两个问题：
* 对于 `worker_thread` / `main js thread` 间并发调用各种 action 不友好
* 需要进行退出前未完结采样动作立即结束并输出文件时由于 dtor 的问题会使得变量信息丢失
此 PR 将 actions 中涉及到的变量放置到 `EnvironmentData` 实例中存储，解决上述问题。
局部逻辑重构，依靠现有 `command.test.js` 保证功能没有 break。
Reference: https://github.com/X-Profiler/xprofiler/pull/202
=> refactor: replace dump actions static storages with EnvironmentData

src/platform/unix/core/linux/elfcore.cc
Save the first page of ELF (including BuildId) to let the debugger find the correct binary it used.
=> feat: save Elf BuildId in corefile.

src/commands/dump.cc, src/commands/dump.h, src/environment_data-inl.h, src/environment_data.cc, src/environment_data.h
1. 合并 `DumpData`，使用 `std::unique_ptr` 明确 owner 语义、避免需要手动释放；
2. 使用 detached 线程，合理回收 profiling watchdog thread.
=> refactor: consolidate dump actions

.eslintrc, README.md, binding.gyp, configuration.js, index.d.ts, src/configure-inl.h, src/hooks/heap_limit.cc, src/hooks/heap_limit.h, src/jsapi/export_hooks.cc, test/fixtures/cases/command.js, test/fixtures/cases/config.js, test/fixtures/cases/limit.js, test/fixtures/scripts/fatal_error.js, test/limit.test.js
增加 `enable_auto_incr_heap_limit` 的配置，默认为 `false` 即不开启此特性。
如果开启 `enable_auto_incr_heap_limit` 为 `true`，则会使得 Node.js 进程在堆分配即将到达上限时可以自动增加 `heap_limit` 续命。
默认每次接近堆上限增加 `256MB` 的 `heap_limit`，这个值可以通过 `auto_heap_limit_size` 来进行修改。
等到 Node.js 进程内存水位恢复正常后使用 `RemoveNearHeapLimitCallback` 重设 `heap_limit` 为 `initial_heap_limit`
=> feat: support auto increase heap limit

src/hooks/heap_limit.cc, test/fixtures/cases/limit.js, test/fixtures/cases/logbypass.js, test/limit.test.js, test/logbypass.test.js
修改自动扩容 `heap_limit` 时的内核日志输出格式，使得其可以被 `xtransit` 解析上报
=> fix: change the heap_limit log format so that it can be parsed

package.json, test/fixtures/cases/command.js, test/fixtures/cases/hooks.js, test/fixtures/utils.js
Commits:
* [36f28a8] fix: change the heap_limit log format so that it can be parsed
* [2fbfea0] fix: restore initial heap limit automatically
* [623b0d2] fix: remove conflict check for heap profiling
=> Release 2.5.1

package.json
Commits:
* [0f4e5a8] feat: support XPROFILER_PREFIX env to set .xprofile dir (#244)
* [2260972] feat: support Node.js v22 (#243)
* [799f075] chore: use npmmirror.com (#240)
=> Release v2.6.1
